### ISSUE TITLE
07 Integración de módulos 

### ISSUE THREAD

**Issue by FDGM** [FDGM/DiplomadoSoftwareEmbebido#9]
- [x] Integración de LCD

- [x] Integración de ADC (Lectura de Potenciometro)

- [x] Integración de PWM (Control del motor)

- [x] Integración de Sensor Hall
